config/routes.rb
Hackweek::Application.routes.draw do

  devise_for :users

  resources :users do
    collection do
      get 'me'
    end
    member do
      post 'keyword', to: "users#add_keyword"
      delete ':keyword', to: "users#delete_keyword", as: "keyword_delete", constraints: { keyword: /[^\/]+/ }
    end
  end

  resources :projects do
    collection do
      get 'archived'
      get 'finished'
      get 'newest'
      get 'popular'
      get 'biggest'
    end
    member do
      match 'like', via: :post
      match 'dislike', via: :post
      match 'join', via: :post
      match 'leave', via: :post
      match 'advance', via: :post
      match 'recess', via: :post
      post 'keyword', to: "projects#add_keyword"
      delete ':keyword', to: "projects#delete_keyword", as: "keyword_delete", constraints: { keyword: /[^\/]+/ }
    end
    resources :comments
  end
  
  resources :comments do
    resources :comments
  end

  resources :announcements do
    member do
      get "enroll" 
    end
  end

  resources :events

  get "keyword/tokens"
  post "api/import", to: "api#import" 
  get "gallery", to: "gallery#index"
  get "search", to: "search#result", as: "search"

  get "front/index"
  get "index.html", to: "front#index"
  get "front/awards"
  get "awards.html", to: "front#awards"
  get "front/howto"
  get "howto.html", to: "front#howto"
  get "front/news"
  get "news.html", to: "front#news"
  
  get 'user_root' => 'users#me'
  root 'front#index'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base

  validates :title, :presence => true
  validates :text, :presence => true
  validates :originator_id, :presence => true

  belongs_to :originator, :class_name => User
  has_many :users, :through => :enrollments
  has_many :enrollments

  def enroll! user
    self.users << user
    self.save!
  end

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController

  load_and_authorize_resource
  skip_before_filter :store_location, :only => [ :enroll ]

  # GET /announcements
  def index
    @announcements = Announcement.all.order("id DESC")
  end

  # GET /announcements/1
  def show
    @announcement = Announcement.find(params[:id])
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  def create
    @announcement = Announcement.new(announcement_params)
    @announcement.originator = current_user

    if @announcement.save
      redirect_to announcements_path
    else
      render action: "new"
    end
  end

  # PUT /announcements/1
  def update
    @announcement = Announcement.find(params[:id])

    if @announcement.update_attributes(announcement_params)
      redirect_to announcements_path
    else
      render action: "edit" 
    end
  end

  # DELETE /announcements/1
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to announcements_path }
      format.js { }
    end
  end

  # GET /annoucements/1/enroll
  def enroll 
    announcement = Announcement.find(params[:id])
    announcement.enroll! current_user

    respond_to do |format|
      format.html{ redirect_to :back }
      format.js { render :partial => "announcement_toggle" }
    end
  end

  def announcement_params
    params.require(:announcement).permit(:title, :text)
  end

end

app/views/announcements/_announcement_toggle.js.erb
$("#announcement-<%= @announcement.id %>").toggle();

app/views/announcements/_file_buttons.html.haml
.btn-group.pull-right
  - if can? :edit, announcement 
    = link_to(edit_announcement_path(announcement), :title=>'Edit this announcement?', :class=> "btn btn-default btn-xs") do
      %i.icon-pencil
  -if can? :destroy, announcement
    = link_to(announcement_path(announcement), :title=>'Delete this announcement?', :class=> "btn btn-default btn-xs", :method => :delete, data: { confirm: "Are you sure you want to delete this announcement for all users? This can't be undone!" }) do
      %i.icon-remove

app/views/announcements/_form.html.haml
= form_for @announcement, html: { role: "form"} do |f|
  - if @announcement.errors.any?
    #error_explanation
      %h2
        = pluralize(@announcement.errors.count, "error")
        prohibited this project from being saved:
      %ul
      - @announcement.errors.full_messages.each do |msg|
        %li
          = msg
  .field
    = f.text_field :title, :placeholder => "The announcements title", :class => 'form-control input-lg', :required => "required"
  .field
    = f.text_area :text, :rows => "20", :placeholder => "Add a announcement text. You can use HTML, please be careful!", :class => 'form-control input-lg'
  .actions
    %p
      = f.submit :class => "btn btn-success pull-right"

app/views/announcements/edit.html.haml
- content_for :title do
  Edit
  = @announcement.title

.col-sm-12
  = render 'form'

app/views/announcements/index.html.haml
- content_for :title do
  Announcements
  = "(#{@announcements.length})"

.col-sm-12
  %h2 Announcements
  %table.table.table-striped
    %thead
      %tr
        %th{:width=>"10%"} Author
        %th{:width=>"75%"} Content
        %th{:width=>"10%"} ACK'd by
        %th{:width=>"5%"} Actions
    - @announcements.each do |announcement|
      %tr
        %td
          = link_to announcement.originator do
            = announcement.originator.name
          %small
            = announcement.updated_at
        %td
          %h3
            = announcement.title
          = simple_format(announcement.text)
        %td
          = pluralize(announcement.users.length, "user")
        %td
          = render :partial => "announcements/file_buttons", :locals => {:announcement => announcement }
  %p
    - if can? :write, Announcement
      = link_to "New announcement", new_announcement_path, :class => "btn btn-success pull-right"

app/views/announcements/new.html.haml
- content_for :title do
  Create Announcement

.col-sm-12
  %h2 Create an Announcement
  %p.help-block
    This will post a new announcement to the header and replace all previous unread announcements.
  = render 'form'

app/views/announcements/show.html.haml
- content_for :title do
  = @announcement.title

.col-sm-12
  %h2
    = @announcement.title
  = simple_format(@announcement.text)