config/routes.rb
Hackweek::Application.routes.draw do

  devise_for :users

  resources :users do
    collection do
      get 'me'
    end
    member do
      post 'keyword', to: "users#add_keyword"
      delete ':keyword', to: "users#delete_keyword", as: "keyword_delete", constraints: { keyword: /[^\/]+/ }
    end
  end

  resources :projects do
    collection do
      get 'archived'
      get 'finished'
      get 'newest'
      get 'popular'
      get 'biggest'
    end
    member do
      match 'like', via: :post
      match 'dislike', via: :post
      match 'join', via: :post
      match 'leave', via: :post
      match 'advance', via: :post
      match 'recess', via: :post
      post 'keyword', to: "projects#add_keyword"
      delete ':keyword', to: "projects#delete_keyword", as: "keyword_delete", constraints: { keyword: /[^\/]+/ }
    end
    resources :comments
  end
  
  resources :comments do
    resources :comments
  end

  resources :announcements do
    member do
      get "enroll" 
    end
  end

  resources :events

  get "keyword/tokens"
  post "api/import", to: "api#import" 
  get "gallery", to: "gallery#index"
  get "search", to: "search#result", as: "search"

  get "front/index"
  get "index.html", to: "front#index"
  get "front/awards"
  get "awards.html", to: "front#awards"
  get "front/howto"
  get "howto.html", to: "front#howto"
  get "front/news"
  get "news.html", to: "front#news"
  
  get 'user_root' => 'users#me'
  root 'front#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :projects
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!, :only => [ :index, :show]

  # GET /events
  def index
    @events = Event.all.order("start DESC")
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to events_path, notice: 'Event was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to events_path, notice: 'Event was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:name, :start, :end)
    end
end

app/views/events/_file_buttons.html.haml
.btn-group.pull-right
  - if can? :edit, event
    = link_to(edit_event_path(event), :title=>'Edit this event?', :class=> "btn btn-default btn-xs") do
      %i.icon-pencil
  -if can? :destroy, event
    = link_to(event_path(event), :title=>'Delete this event?', :class=> "btn btn-default btn-xs", :method => :delete, data: { confirm: "Are you sure you want to delete this event? This can't be undone!" }) do
      %i.icon-remove

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.text_field :name, :placeholder => "Name", :class => 'form-control input-lg'
  .field
    = f.date_field :start, :placeholder => "Start Date (YYYY-MM-DD)", :required => "required", :class => 'form-control input-lg'
  .field
    = f.date_field :end, :placeholder => "End Date (YYYY-MM-DD)", :required => "required", :class => 'form-control input-lg'
  .actions
    %p
      = f.submit :class => "btn btn-success pull-right"

app/views/events/edit.html.haml
- content_for :title do
  Edit
  = @event.name

.col-sm-12
  %h2
    Edit
    = @event.name
  = render 'form'

app/views/events/index.html.haml
- content_for :title do
  Events

.col-sm-12
  - if @events.length > 0
    .row
      .col-sm-12
        %table.table#events_table
          %thead
            %th Name
            %th Date
            %th Actions
          - @events.each do |event|
            %tr
              %td
                = link_to event_path(event) do
                  = event.name.titleize
              %td
                = "#{event.start} - #{event.end}"
              %td
                = render :partial => "events/file_buttons", :locals => {:event => event }
  %p
    - if can? :write, Event
      = link_to "New event", new_event_path, :class => "btn btn-success pull-right"

app/views/events/new.html.haml
- content_for :title do
  Create Event

.col-sm-12
  %h2 Create an Event
  %p.help-block
  = render 'form'

app/views/events/show.html.haml
- content_for :title do
  = @event.name

.col-sm-12
  %h2
    = @event.name
  %p
    From
    = @event.start
    to
    = @event.end