config/routes.rb
Hackweek::Application.routes.draw do

  devise_for :users

  resources :users do
    collection do
      get 'me'
    end
    member do
      post 'keyword', to: "users#add_keyword"
      delete ':keyword', to: "users#delete_keyword", as: "keyword_delete", constraints: { keyword: /[^\/]+/ }
    end
  end

  resources :projects do
    collection do
      get 'archived'
      get 'finished'
      get 'newest'
      get 'popular'
      get 'biggest'
    end
    member do
      match 'like', via: :post
      match 'dislike', via: :post
      match 'join', via: :post
      match 'leave', via: :post
      match 'advance', via: :post
      match 'recess', via: :post
      post 'keyword', to: "projects#add_keyword"
      delete ':keyword', to: "projects#delete_keyword", as: "keyword_delete", constraints: { keyword: /[^\/]+/ }
    end
    resources :comments
  end
  
  resources :comments do
    resources :comments
  end

  resources :announcements do
    member do
      get "enroll" 
    end
  end

  resources :events

  get "keyword/tokens"
  post "api/import", to: "api#import" 
  get "gallery", to: "gallery#index"
  get "search", to: "search#result", as: "search"

  get "front/index"
  get "index.html", to: "front#index"
  get "front/awards"
  get "awards.html", to: "front#awards"
  get "front/howto"
  get "howto.html", to: "front#howto"
  get "front/news"
  get "news.html", to: "front#news"
  
  get 'user_root' => 'users#me'
  root 'front#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  include AASM

  validates :title, :presence => true
  validates :description, :presence => true
  validates :originator_id, :presence => true
  
  belongs_to :originator, :class_name => User

  has_many :users, :through => :memberships
  has_many :kudos, :through => :likes, :source => :user

  has_many :project_interests
  has_many :keywords, :through => :project_interests
  
  has_many :memberships
  has_many :likes
  has_many :updates, dependent: :destroy

  has_many :comments, :as => :commentable

  has_and_belongs_to_many :events

  after_create :create_initial_update

  aasm do
    state :idea, :initial => true
    state :project
    state :invention
    state :record
    
    event :advance do
      transitions :from => [:idea], :to => :project
      transitions :from => [:project], :to => :invention
      transitions :from => [:record], :to => :idea
    end

    event :recess do 
      transitions :from => [:project], :to => :idea
      transitions :from => [:idea], :to => :record
      transitions :from => [:invention], :to => :project
    end

    event :abandon do 
      transitions :from => [:project], :to => :idea
      transitions :from => [:invention], :to => :invention
    end

  end

  # solr configuration
  searchable do
    text :title
    text :description
  end

  
  def join! user
    if self.users.empty?
      started = true
    end

    self.users << user
    self.save!

    if started
      self.advance!
      Update.create!(:author => user,
                     :text => "started",
                     :project => self)
    else
      Update.create!(:author => user,
                     :text => "joined",
                     :project => self)
    end
  end
  
  def leave! user
    self.users -= [ user ]
    self.save!
    
    # If the last user has left...
    if self.users.empty?
      self.abandon!
    end

    Update.create!(:author => user,
                   :text => "left",
                   :project => self)
  end
  
  def like! user
    self.kudos << user
    self.save!

    Update.create!(:author => user,
                   :text => "liked",
                   :project => self)
  end
  
  def dislike! user
    self.kudos -= [ user ]
    self.save!

    Update.create!(:author => user,
                   :text => "disliked",
                   :project => self)
  end
  
  def add_keyword! name, user
    name.downcase!
    name.gsub! /\s/, "" 
    keyword = Keyword.find_by_name name
    if !keyword
      keyword = Keyword.create! :name => name
    end
    if !self.keywords.include? keyword
      self.keywords << keyword
      save!
    end

    Update.create!(:author => user,
                   :text => "added keyword \"#{name}\" to",
                   :project => self)
  end

  def remove_keyword! name, user
    keyword = Keyword.find_by_name name
    if self.keywords.include? keyword
      self.keywords.delete(keyword)
      save!
    end

    Update.create!(:author => user,
                   :text => "removed keyword #{name} from",
                   :project => self)
  end

  def create_initial_update
    Update.create!(:author => self.originator,
                   :text => "originated",
                   :project => self)
  end

  def previous
    Project.where('id < ?', self.id).last
  end

  def next
    Project.where('id > ?', self.id).first
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  load_and_authorize_resource
  skip_before_filter :authenticate_user!, :only => [ :index, :show, :archived, :finished, :newest, :popular, :biggest ]
  skip_before_filter :store_location, :only => [:join, :leave, :like, :dislike, :add_keyword, :delete_keyword ]
  skip_before_action :verify_authenticity_token, :only => [:add_keyword, :delete_keyword ]

  # GET /projects
  def index
    @projects = Project.where.not(aasm_state: "record").where.not(aasm_state: "invention")
  end

  # GET /projects/archived
  def archived
    @projects = Project.where(aasm_state: "record")
    render "index"
  end

  # GET /projects/finished
  def finished
    @projects = Project.where(aasm_state: "invention").order("updated_at DESC")
    render "index"
  end

  # GET /projects/newest
  def newest
    @projects = Project.where.not(aasm_state: "record").order("created_at DESC LIMIT 10")
    render "index"
  end

  # GET /projects/popular
  def popular
    @projects = Project.where("likes_count > 0").where.not(aasm_state: "record").order("likes_count DESC")
    render 'index'
  end

  # GET /projects/biggest
  def biggest
    @projects = Project.where("memberships_count > 0").where.not(aasm_state: "record").order("memberships_count DESC")
    render 'index'
  end

  # GET /projects/1
  def show
    @project = Project.find(params[:id])
    @new_comment = Comment.new
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    @project.originator = current_user

    if @project.save
      redirect_to @project
    else
      render action: "new"
    end
  end

  # PUT /projects/1
  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      redirect_to @project
    else
      render action: "edit" 
    end
  end

  # DELETE /projects/1
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_path }
      format.js { }
    end
  end

  # PUT /projects/1/advance
  def advance
    project = Project.find(params[:id])
    project.advance!

    respond_to do |format|
      format.html { redirect_to project }
      format.js { }
    end
  end

  # PUT /projects/1/recess
  def recess
    project = Project.find(params[:id])
    project.recess!

    respond_to do |format|
      format.html { redirect_to project }
      format.js { }
    end
  end

  # PUT /projects/1/join
  def join
    project = Project.find(params[:id])
    if project.aasm_state == "invention"
      redirect_to project, error: "You can't join this project as it's finished."
    end
    project.join! current_user

    respond_to do |format|
      format.html{ redirect_to project, notice: "Welcome to the project #{current_user.name}!" }
      format.js {}
    end
  end

  # PUT /projects/1/leave
  def leave
    project = Project.find(params[:id])
    if project.aasm_state == "invention"
      redirect_to project, error: "You can't leave this project as it's finished."
    end
    project.leave! current_user

    respond_to do |format|
      format.html{ redirect_to project, notice: "Goodbye #{current_user.name}..." }
      format.js {}
    end
  end

  # PUT /projects/1/like
  def like
    project = Project.find(params[:id])
    project.like! current_user

    respond_to do |format|
      format.html{ redirect_to project, notice: "Thank you for your love #{current_user.name}!" }
      format.js { render :partial => "like_toggle" }
    end
  end

  # PUT /projects/1/dislike
  def dislike
    project = Project.find(params[:id])
    project.dislike! current_user
    
    respond_to do |format|
      format.html{ redirect_to project, notice: "Aaww Snap! You don't love me anymore?" }
      format.js { render :partial => "like_toggle" }
    end
  end

  # PUT /projects/1/add_keyword
  def add_keyword
    project = Project.find(params[:id])
    keywords = keyword_params.split(',')
    keywords.each do |word|
      project.add_keyword! word, current_user
    end

    respond_to do |format|
      format.html{ redirect_to project }
      format.js {}
    end
  end

  # PUT /projects/1/delete_keyword
  def delete_keyword
    project = Project.find(params[:id])
    keywords = keyword_params.split(',')
    keywords.each do |word|
      project.remove_keyword! word, current_user
    end

    respond_to do |format|
      format.html{ redirect_to project }
      format.js {}
    end
  end

  def project_params
    params.require(:project).permit(:description, :title)
  end

  def keyword_params
    params.require(:keyword)
  end

end

app/views/projects/_file_buttons.html.haml
.btn-group
  - if can? :edit, project
    = link_to(edit_project_path(project), :title=>'Edit this project?', :class=> "btn btn-default") do
      %i.icon-pencil
    - if project.may_advance?
      - case project.aasm_state
        - when "project"
          =link_to(advance_project_path(project), :method => :post,:title=>'Finish this project', :class=> "btn btn-default") do
            %i.icon-check
        - when "record"
          =link_to(advance_project_path(project), :method => :post,:title=>'Revive this project', :class=> "btn btn-default") do
            %i.icon-bolt
    - if project.may_recess?
      - case project.aasm_state
        - when "idea"
          =link_to(recess_project_path(project), :method => :post,:title=>'Archive this project', :class=> "btn btn-default") do
            %i.icon-archive
        - when "invention"
          =link_to(recess_project_path(project), :method => :post,:title=>"Restart this project", :class=> "btn btn-default") do
            %i.icon-lightbulb
  -if can? :destroy, project
    = link_to(project_path(project), :title=>'Delete this project?', :class=> "btn btn-default", :method => :delete, data: { confirm: "Are you sure you want to delete this project? This can't be undone!" }) do
      %i.icon-remove

app/views/projects/_form.html.haml
= render :partial => 'comments/help'
= form_for @project, html: { role: "form"} do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = pluralize(@project.errors.count, "error")
        prohibited this project from being saved:

      %ul
      - @project.errors.full_messages.each do |msg|
        %li
          = msg
  .field
    = f.text_field :title, :placeholder => "The projects title", :class => 'form-control input-lg', :required => "required"
    
  .field
    = f.text_area :description, :rows => "20", :placeholder => "Add a detailed description of your idea. You can use markdown.", :class => 'form-control input-lg'
  .actions
    %p
      = f.submit :class => "btn btn-success pull-right"

app/views/projects/_info.html.haml
Last updated
= "#{time_ago_in_words project.created_at}"
ago.
- if project.kudos.length > 0
  Captured
  = pluralize(project.kudos.length, "hackers heart.", "hacker hearts.")
-else 
  No love.
- if project.users.empty?
  No hacker. How about you
  = link_to 'grab it!', join_project_path(project.id), :method => :post

app/views/projects/_like_button.html.haml
- project = @project if @project
- dislike = "display: none;" unless project.kudos.include? current_user
= link_to(dislike_project_path(project.id), :method => :post, :title=>'Dislike this project?', :class=> "btn btn-default btn-xs", :id => "dislike-#{project.id}", :style => "#{dislike}", :remote=>true) do
  %i.icon-heart{:style => "color: #73ba25;"}
- like = "display: none;" if project.kudos.include? current_user
=link_to(like_project_path(project.id), :method => :post,:title=>'Like this project', :class=> "btn btn-default btn-xs", :id => "like-#{project.id}", :style => "#{like}", :remote => true) do
  %i.icon-heart-empty

app/views/projects/_like_toggle.js.erb
$("#like-<%= @project.id %>").toggle();
$("#dislike-<%= @project.id %>").toggle();

app/views/projects/_list_item.html.haml
%h4.project-list-item{:id => "project-#{index}"}
  = link_to project_path(project) do
    = project.title
%p{:style=>"margin-top: -10px"}
  %small
    = render :partial => "projects/state_name", :locals => {:project => project }
    by
    = link_to(user_path(project.originator.id)) do
      #{project.originator.name}
      = render :partial => "projects/like_button", :locals => {:project => project }
:markdown
  #{truncate(project.description, length: 140)}
- unless project.users.empty?
  .well.well-sm
    - project.users.each do |user|
      = link_to user_path(user) do
        = image_tag(user.gravatar_url(:size => "24"), :class => "img-thumbnail", :title => "#{user.name}", :alt => user.name)
%span.help-block
  %small
    = render :partial => "projects/info", :locals => {:project => project }

app/views/projects/_state_name.html.haml
- case project.aasm_state
  - when "idea"
    an
  - when "invention"
    an
  - else
    a
= project.aasm_state

app/views/projects/_tabs.html.haml
%ul.nav.nav-tabs
  - all_state = "active" if action_name == "index"
  %li{:class => all_state}
    =link_to projects_path, :title => "All projects" do
      All
      - if all_state === "active"
        =  "(#{@projects.length})"
  - newest_state = "active" if action_name == "newest"
  %li{:class => newest_state}
    =link_to newest_projects_path, :title => "Most recent projects" do
      Newest
      - if newest_state === "active"
        =  "(#{@projects.length})"
  - popular_state = "active" if action_name == "popular"
  %li{:class => popular_state}
    =link_to popular_projects_path, :title => "Most liked projects" do
      Popular
      - if popular_state === "active"
        =  "(#{@projects.length})"
  - biggest_state = "active" if action_name == "biggest"
  %li{:class => biggest_state}
    =link_to biggest_projects_path, :title => "Most active projects" do
      Biggest
      - if biggest_state === "active"
        =  "(#{@projects.length})"
  - archived_state = "active" if action_name == "archived"
  %li{:class => archived_state}
    =link_to archived_projects_path, :title => "Dismissed projects" do
      Archived
      - if archived_state === "active"
        =  "(#{@projects.length})"
  - finished_state = "active" if action_name == "finished"
  %li{:class => finished_state}
    =link_to finished_projects_path, :title => "Finished projects" do
      Finished
      - if finished_state === "active"
        =  "(#{@projects.length})"

app/views/projects/_tile.html.haml
.panel.panel-info
  .panel-heading
    %h3.panel-title
      = link_to project_path(project) do
        = project.title
        = render :partial => "projects/like_button", :locals => {:project => project }
  .panel-body
    :markdown
      #{truncate(project.description, length: 140)}
    .user-list{:style=>"padding-top: 10px;"}
      - if project.users.empty?
        .alert.alert-warning
          Holy moly! This project has no developer yet and is up for
          = link_to 'grabs!', join_project_path(project.id), :class => "alert-link"
      - else
        .well.well-sm
          - project.users.each do |user|
            = link_to user_path(user) do
              = image_tag(user.gravatar_url(:size => "24"), :class => "img-thumbnail", :title => "#{user.name}", :alt => user.name)
  .panel-footer
    %small
      an idea by
      = link_to(user_path(project.originator.id)) do
        #{project.originator.name},
      updated
      = "#{time_ago_in_words project.updated_at}"
      ago

app/views/projects/edit.html.haml
- content_for :title do
  Edit
  = @project.title

.col-sm-12.project
  = render 'form'

app/views/projects/index.html.haml
- content_for :title do
  = action_name.humanize unless action_name === "index"
  Projects
  = "(#{@projects.length})"

.col-sm-12
  = render :partial => "projects/tabs"
  .tab-content{:style => "padding-top: 10px;"}
    - if @projects.length > 0
      .tab-pane.active
        .row.project-list-pills{:style=> "padding-bottom: 10px;"}
          .col-sm-6
            #table_search
          .col-sm-6
            %ul.nav.nav-pills.pull-right
              %li.active#all-pill
                %a{:href =>"#", :id=>"all", :title=> "All Projects"}
                  All
              %li#ideas-pill
                %a{:href =>"#", :id=>"ideas", :title => "Projects nobody is working on"}
                  %i.icon-lightbulb
                  Ideas
              %li#projects-pill
                %a{:href =>"#", :id=>"projects", :title => "Projects people are working on"}
                  %i.icon-puzzle-piece
                  Projects
        .row
          .col-sm-12
            %table.table#project_table
              %thead
              - @projects.each_with_index do |project, index|
                %tr
                  %td{:class => "#{project.aasm_state}"}
                    = render :partial => "projects/list_item", :locals => {:project => project, :index => index }
    - else
      .row
        .col-sm-12
          %h3
            No projects. How about you
            = link_to "add one!", new_project_path

- content_for :script do
  :javascript
    $( "#ideas" ).click(function() {
      console.log ("show only ideas");
      $( ".project" ).hide();
      $( ".idea" ).show();
      $( "#ideas-pill").addClass( "active" );
      $( "#all-pill, #projects-pill").removeClass( "active" );
    });
    $( "#projects" ).click(function() {
      console.log ("show only projects");
      $( ".idea" ).hide();
      $( ".project" ).show();
      $( "#projects-pill").addClass( "active" );
      $( "#all-pill, #ideas-pill").removeClass( "active" );
    });
    $( "#all" ).click(function() {
      console.log ("show everything");
      $( ".idea" ).show();
      $( ".project" ).show();
      $( "#all-pill").addClass( "active" );
      $( "#projects-pill, #ideas-pill").removeClass( "active" );
    });
    $("table").addTableFilter({
    });

    Mousetrap.bind('j', function() { ProjectNext(); });
    Mousetrap.bind('k', function() { ProjectPrevious(); });

    function ProjectPrevious() {  
        hash = window.location.hash
        all = $("h4[id^='project-']").length
        if (hash == "")
          window.location.hash = "#project-0";
        else
          var blah = hash.split('-')
        next = parseInt(blah[1])
        if(next > 0)
          next--
        else
          next = all - 1
        window.location.hash = "#project-" + next;
      }

    function ProjectNext() {  
      hash = window.location.hash
      all = $("h4[id^='project-']").length
      if (hash == "")
        window.location.hash = "#project-0";
      else
        var blah = hash.split('-')
      next = parseInt(blah[1])
      if(next == (all - 1))
        next = 0
      else
        next++
      window.location.hash = "#project-" + next;
    }

app/views/projects/new.html.haml
- content_for :title do
  Create Project

.col-sm-12.project
  %h2 Create a project
  = render 'form'

app/views/projects/show.html.haml
- content_for :title do
  = @project.title

.col-sm-12
  .row
    .col-sm-12
      - if @project.previous
        =   button_to 'Previous', @project.previous, :id => "previous_link", :method => :get, :class => "btn btn-default btn-xs pull-left", :title=> "Try pressing 'j' on your keyboard.."
      - if @project.next
        = button_to 'Next', @project.next, :id => "next_link", :method => :get, :class => "btn btn-default btn-xs pull-right", :title => "Try pressing 'k' on your keyboard.."
      .clearfix
      .page-header
        %h1
          = @project.title
          %br
          %small
            = render :partial => "projects/state_name", :locals => {:project =>  @project }
            by
            = link_to user_path(@project.originator) do
              = @project.originator.name
            = render :partial => "projects/like_button", :locals => {:project =>  @project }
        %span.help-block
          %small
            = render :partial => "projects/info", :locals => {:project => @project }
  .row
    .col-sm-8
      :markdown
        #{@project.description}
    .col-sm-4
      .row
        .col-sm-12
          .text-right
            = render :partial => "projects/file_buttons", :locals => {:project =>  @project }
        .col-sm-12
          %h4
            - if @project.users.empty?
              No
            Hackers
          .well.well-sm
            - @project.users.each do |user|
              = link_to(user_path(user.id)) do
                = image_tag user.gravatar_url(:size => "64"), alt: user.name, title: user.name, class: "img-thumbnail"
          - unless @project.aasm_state == "invention"
            - if @project.users.empty? or !@project.users.include? current_user
              = link_to(join_project_path(@project), :method => :post, :class => "btn btn-success") do
                Join this project
            - if @project.users.include? current_user
              = link_to(leave_project_path(@project), :method => :post, :class => "btn btn-warning") do
                Leave this project
        .col-sm-12
          %h4 Looking for mad skills in:
          - if @project.keywords.empty?
            %p Nothing? Add some keywords!
          - else 
            %p
              = render :partial => "keywords/show", :locals => {:keywords =>  @project.keywords }
          -if  @project.originator == current_user or @project.users.include? current_user
            %p
              = render :partial => "keywords/new", :locals => {:what => @project }
        .col-sm-12
          %h4
            Activity
            %span.pull-right
              = render :partial => "updates/show_all_modal", :locals => { :updates => @project.updates }
          %ul
          - @project.updates.reverse.first(5).each do |update|
            %li
              = render :partial => "updates/show", :locals => { :update => update }
  .row
    .col-sm-12
      %h4
        Comments
      %ul.media-list
        = render :partial => 'comments/comment', :collection => @project.comments
      %p
        - if current_user
          = render :partial => 'comments/help'
          = form_for [ @project, @new_comment ], html: {role: "form"} do |f|
            %p
            = f.text_area :text, :placeholder => "Your comment. You can use markdown.", :class => 'form-control input-lg', :required => "required"
            %p
            = button_tag(type: 'submit', class: "btn btn-success pull-right") do
              %i.icon-plus-sign
              Add Comment
        - else
          = link_to 'Add a comment', new_project_comment_path( @project ), :class => 'btn btn-default'

- content_for :script do
  :javascript
    Mousetrap.bind('j', function() { $('#previous_link').click(); });
    Mousetrap.bind('k', function() { $('#next_link').click(); })