config/routes.rb
Hackweek::Application.routes.draw do

  devise_for :users

  resources :users do
    collection do
      get 'me'
    end
    member do
      post 'keyword', to: "users#add_keyword"
      delete ':keyword', to: "users#delete_keyword", as: "keyword_delete", constraints: { keyword: /[^\/]+/ }
    end
  end

  resources :projects do
    collection do
      get 'archived'
      get 'finished'
      get 'newest'
      get 'popular'
      get 'biggest'
    end
    member do
      match 'like', via: :post
      match 'dislike', via: :post
      match 'join', via: :post
      match 'leave', via: :post
      match 'advance', via: :post
      match 'recess', via: :post
      post 'keyword', to: "projects#add_keyword"
      delete ':keyword', to: "projects#delete_keyword", as: "keyword_delete", constraints: { keyword: /[^\/]+/ }
    end
    resources :comments
  end
  
  resources :comments do
    resources :comments
  end

  resources :announcements do
    member do
      get "enroll" 
    end
  end

  resources :events

  get "keyword/tokens"
  post "api/import", to: "api#import" 
  get "gallery", to: "gallery#index"
  get "search", to: "search#result", as: "search"

  get "front/index"
  get "index.html", to: "front#index"
  get "front/awards"
  get "awards.html", to: "front#awards"
  get "front/howto"
  get "howto.html", to: "front#howto"
  get "front/news"
  get "news.html", to: "front#news"
  
  get 'user_root' => 'users#me'
  root 'front#index'

end

app/views/layouts/_alert.html.haml
- flash.each do |type, message|
  %div{:class=>"alert alert-dismissable #{bootstrap_class_for(type)}", :id=>"flash"}
    .button.close{"data-dismiss" => "alert", "aria-hidden"=>"true"}
      &times;
    %h3
      = message

app/views/layouts/_footer.html.haml
%footer
  .container
    .row
      .col-sm-4
        %h3
          About Hack Week
        %p{:style=>"text-align: justify;"}
          Hack Week is the week where
          %strong SUSE
          engineers can experiment without limits. It's your opportunity to innovate, collaborate across teams, and learn.
          Do what you want, but do it!
        %ul.nav.nav-pills
          %li
            = link_to(front_news_path) do
              %i.icon-bullhorn
              News
          %li
            = link_to(front_howto_path) do
              %i.icon-question
              Help
          %li
            = link_to(front_awards_path) do
              %i.icon-certificate
              Awards
          %li
            = link_to(gallery_path) do
              %i.icon-picture
              Pictures
      .col-sm-2.col-sm-offset-6.hidden-xs.text-center
        %h3 &nbsp;
        = link_to "http://www.suse.com" do
          = image_tag  "suse_logo_w-tag_black.png", :class => "img-responsive", :alt => "SUSE logo" , :title => "Enterprise Linux you can rely on"
    .row
      .col-sm-12.text-center
        %small
          &copy; 2013 SUSE.
          This tool is
          = link_to "free software,", "http://www.gnu.org/philosophy/free-sw.html"
          you can run, copy, distribute, study, change and improve it.
          The source code and the developers are on
          = link_to "github.", "https://github.com/SUSE/hackweek"

app/views/layouts/_header.html.haml
%header.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  / Brand and toggle get grouped for better mobile display
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to(root_path, {:name => "top", :class => "navbar-brand"}) do
        = image_tag("suse-logo-sketch.png", :width => "32px", :alt => "Home", :title => 'Hack Week Front Page')
    / Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse.navbar-ex1-collapse
      %ul.nav.navbar-nav
        %li
          = link_to(projects_path, {:id=>"projects_path", :alt=>"Projects", :title=>"List all Projects"}) do
            %i.icon-puzzle-piece
            Projects
        %li
          = link_to(users_path, :id=>"users_path") do
            %i.icon-user
            People
        - if user_signed_in?
          - if current_user.role? :organizer
            %li
              = link_to(announcements_path, :id=>"announcements_path") do
                %i.icon-bullhorn
                Announcements
            %li
              = link_to(events_path, :id => "events_path") do
                %i.icon-calendar
                Events
            %ul.nav.navbar-nav.navbar-right
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :id => "user-dropdown"}
                  %i.icon-plus-sign-alt.icon
                  Create
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to(new_project_path, :id => "new_project_path") do
                      %i.icon-puzzle-piece
                      Project
                  %li
                    = link_to(new_announcement_path, :id => "new_announcement_path") do
                      %i.icon-bullhorn
                      Announcement
                  %li
                    = link_to(new_event_path, :id => "new_event_path") do
                      %i.icon-calendar
                      Event
          - else 
            %li
              = link_to(new_project_path, {:id=>"new_project_path",:alt=>"Add Project", :title=>"Add Project"}) do
                %i.icon-plus-sign-alt.icon
                Create
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right.hidden-xs
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :id => "user-dropdown"}
              = image_tag(current_user.gravatar_url(:size => "22"), :title => "Yo #{current_user.name}!")
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to(me_users_path, :id => "me_users_path") do
                  %i.icon-home
                  = current_user.name
              %li
                = link_to(destroy_user_ichain_session_path, :method => :delete, :id => "logout-link") do
                  %i.icon-off
                  Log out
        %ul.nav.navbar-nav.navbar-right.visible-xs
          %li
            = link_to(me_users_path) do
              %i.icon-home
              = current_user.name
          %li
            = link_to(destroy_user_ichain_session_path, :method => :delete, :id => "logout-link") do
              %i.icon-off
              Log out
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to(new_user_ichain_session_path, :id => "login-link") do
              %i.icon-signin
              Sign In
      %form{:role=>"search", :method=>"get", :class=>"navbar-form navbar-right", :action=>"#{search_path}", "accept-charset"=>"UTF-8"}
        .form-group
        = search_field_tag(:q, nil, {:class => "form-control", :placeholder => "Search", :type => "search", :name => "q"})

app/views/layouts/_news.html.haml
%div{:class=>"alert alert-info", :id=> "announcement-#{@news.id}"}
  .media.text-center
    = render :partial => "announcements/file_buttons", :locals => {:announcement =>  @news }
    .media-body
      %h3.media-heading
        = @news.title
      = simple_format(@news.text)
      = button_to 'Got it!', enroll_announcement_path(@news), :method => :get, :remote=>true, :class => "btn btn-success pull-right", :title=> "Dismiss this announcement"

app/views/layouts/_scripts.html.haml
:javascript
  var pkBaseURL = (("https:" == document.location.protocol) ? "https://beans.opensuse.org/piwik/" : "http://beans.opensuse.org/piwik/");
  document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
:javascript
  try {
    var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 23);
    piwikTracker.trackPageView();
    piwikTracker.enableLinkTracking();
  } catch( err ) {}
%noscript
  %p
    %img{:src=>"http://beans.opensuse.org/piwik/piwik.php?idsite=23", :style=>"border:0", :alt=>''}

app/views/layouts/application.html.haml
%html{:xmlns => "http://www.w3.org/1999/html"}
  %head
    %title
      - if content_for?(:title)
        Hack Week:
        = yield(:title)
      -else
        Hack Week
    %meta{:charset=> "utf-8"}
    %meta{:name => "viewport", :content =>"width=device-width, initial-scale=1.0"}
    = favicon_link_tag 'favicon.gif'
    = stylesheet_link_tag "application", :media => "all"
    %meta{:property => "og:title", :content => "SUSE Hack Week"}
    %meta{:property => "og:image", :content => "http://hackweek.suse.com/images/hackweek-logo-10.png"}
    %meta{:property => "og:site_name", :content => "SUSE Hack Week"}
    %meta{:property => "og:description", :content => "Hack Week is the week where SUSE engineers can experiment without limits. This is the opportunity to innovate, collaborate across teams, and learn."}
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .wrap
      = render :partial => "layouts/header"
      .clear-top
        .container
          - if flash
            = render partial: "layouts/alert", flash: flash
          - if @news
            = render partial: "layouts/news"
          .row.content
            = yield
    = render :partial => "layouts/footer"
    = render :partial => "layouts/scripts"
    = yield :script

app/views/layouts/front.html.haml
%html{:xmlns => "http://www.w3.org/1999/html"}
  %head
    %title Hackweek 
    %meta{:charset=> "utf-8"}
    %meta{:name => "viewport", :content =>"width=device-width, initial-scale=1.0"}
    = favicon_link_tag 'favicon.gif'
    = stylesheet_link_tag "front", :media => "all"
    %meta{:property => "og:title", :content => "SUSE Hack Week 9"}
    %meta{:property => "og:image", :content => "http://hackweek.suse.com/images/suse-hackweek-9.png"}
    %meta{:property => "og:site_name", :content => "SUSE Hack Week 9"}
    %meta{:property => "og:description", :content => "Hack Week is the week where SUSE engineers can experiment without limits. This is the opportunity to innovate, collaborate across teams, and learn."}
    %script{:type=>"text/javascript", :src=>"https://platform.twitter.com/widgets.js"}
    = javascript_include_tag "front"
    = csrf_meta_tags
  %body
    - if flash
      = render partial: "layouts/alert", flash: flash
      = yield
    :javascript
      var pkBaseURL = (("https:" == document.location.protocol) ? "https://beans.opensuse.org/piwik/" : "http://beans.opensuse.org/piwik/");
      document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));

    :javascript
      try {
        var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 23);
        piwikTracker.trackPageView();
        piwikTracker.enableLinkTracking();
      } catch( err ) {}

    %noscript
      %p
        %img{:src=>"http://beans.opensuse.org/piwik/piwik.php?idsite=23", :style=>"border:0", :alt=>""}